pipeline {
    agent any

    environment {
        GCP_PROJECT_ID = 'nitesh-gcp-444718'
        GKE_CLUSTER = 'microservices-cluster'
        GKE_ZONE = 'us-central1-c'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/<your-repo>/microservice.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t gcr.io/$GCP_PROJECT_ID/microservice-app:latest .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push gcr.io/$GCP_PROJECT_ID/microservice-app:latest'
            }
        }

        stage('Deploy to GKE') {
            steps {
                sh 'gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE'
                sh 'helm upgrade --install microservice ./microservice-chart'
            }
        }
    }
}