pipeline {
    agent any

    environment {
        GCP_PROJECT_ID = 'nitesh-gcp-444718'
        GKE_CLUSTER = 'microservices-cluster'
        GKE_ZONE = 'us-central1-c'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/niteshkumarm287/devops-1.1'
            }
        }

        stage('Deploy to GKE') {
            steps {
                script {
                    echo "Deploying to GKE..."
                    sh 'gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE'
                    sh 'helm upgrade --install microservice ./helm-charts/microservice-chart'
                }
            }
        }
    }
}
