name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Version
        id: version
        run: |
          # Start with v1 and increment based on commit count
          VERSION="v$(git rev-list --count HEAD)"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Extract Git SHA
        id: git_sha
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        id: build_image
        run: |
          # Generate timestamps and image SHA
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")
          IMAGE_SHA=$(docker image inspect --format '{{.Id}}' $(docker build -q simple_python_app/) | cut -d ':' -f2 | head -1)

          # Generate the full image tag
          IMAGE_TAG="${{ env.version }}-git-${GITHUB_ENV_sha}-image-${IMAGE_SHA}-${TIMESTAMP}"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image-name:${{ env.image_tag }} simple_python_app/

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:${{ env.image_tag }}

      - name: Output Docker Image Tag
        run: |
          echo "Docker image pushed with tag: ${{ env.image_tag }}"
