apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: gcr.io/nitesh-gcp-444718/gcpdevops:latest
          ports:
            - containerPort: 8080
