apiVersion: v1
kind: {{ .Values.persistentVolume.kind }}
metadata:
  name: {{ .Values.persistentVolume.metadata.name }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.spec.accessModes | first }}
  capacity:
    storage: {{ .Values.persistentVolume.spec.capacity.storage }}
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistentVolume.spec.hostPath.path }}