apiVersion: v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.metadata.name }}
spec:
  accessModes:
    - {{ .Values.spec.accessModes 0 }}
  capacity:
    storage: {{ .Values.spec.capacity.storage }}
  storageClassName: standard
  hostPath:
    path: {{ .Values.spec.hostPath.path }}