apiVersion: v1
kind: {{ .Values.persistentVolumeClaim.kind }}
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
    - {{ index .Values.persistentVolumeClaim.spec.accessModes 0 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.spec.resources.requests.storage }}
  storageClassName: {{ .Values.persistentVolumeClaim.spec.storageClassName }}
  volumeName: {{ .Values.persistentVolumeClaim.spec.volumeName }}