replicaCount: 2

image:
  repository: nitesh287/fastapi
  tag: "12597977546"
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service
