replicaCount: 2

image:
  repository: nitesh287/my-fastapi-image-1
  tag: "12598445213"
  pullPolicy: IfNotPresent

podLabels:
  app: simple-deployment

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: simple-deployment-service
