replicaCount: 2

image:
  repository: nitesh287/my-fastapi-image-1
  tag: "71c446a"
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service
