replicaCount: 2

image:
  repository: my-fastapi-image-1
  tag: "12598240392"
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service
