apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  annotations:
    owner: "Nitesh Kumar M"
    purpose: "Application configuration for my-app"
data:
  APP_ENV: production
  LOG_LEVEL: info