apiVersion: networking.k8s.io/v1
kind: {{ .Values.ingress.kind }}
metadata:
  name: {{ .Values.ingress.metadata.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "35.188.164.152"
      http:
        paths:
          - path: {{ index .Values.ingress.spec.rules 0 "http" "paths" 0 "path" }}
            pathType: {{ index .Values.ingress.spec.rules 0 "http" "paths" 0 "pathType" }}
            backend:
              service:
                name: {{ .Values.ingress.metadata.name }}-service
                port:
                  number: {{ index .Values.ingress.spec.rules 0 "http" "paths" 0 "backend" "service" "port" "number" }}
  tls:
    - hosts:
        - "35.188.164.152"
      secretName: app-tls-secret