deployment:
  kind: Deployment
  metadata:
    name: my-deployment
  spec:
    replicas: 2
    containers:
    - name: my-container
      image: nginx
      tag: latest
      volumeMounts:
      - mountPath: /data
        name: data
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc

persistentVolume:
  kind: PersistentVolume
  metadata:
    name: demo-pv
    labels:
      app: my-deployment  # Correct map
  spec:
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: 10Mi
    storageClassName: standard
    hostPath:
      path: /tmp/demo-pv

persistentVolumeClaim:
  kind: PersistentVolumeClaim
  metadata:
    name: demo-pvc
    labels:
      app: my-deployment  # Correct map
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
    storageClassName: standard
    volumeName: demo-pv
