apiVersion: v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.metadata }}
spec:
  containers:
    - name: {{ .Values.metadata }}-container
      image: {{ index .Values.containers 0 "image" }}:{{ index .Values.containers 0 "tag" }}
