apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: prod
  annotations:
    argocd-image-updater.argoproj.io/image-list: nitesh287/my-image-name
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nitesh287/my-image-name:version-git--image-15f5e401085dd7420f94f1ee61d49fb54768adde2dfdc090ab78826002ff5522-2025-01-01T02-55-57
