apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: nitesh287/my-image-name
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: mydockerhubuser/myapp:v1-git--image-29758df89526a4f0b95f606b619b5202f6ceb89f9aa19fffa0ee50dbd6fd9d42-2025-01-01T03-01-18
