apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: prod
  annotations:
    argocd-image-updater.argoproj.io/image-list: nitesh287/my-image-name
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: branch:main  # Specify the target branch to commit the changes
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest  # Update the deployment with the latest image tag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        # Dynamic image tag which will be updated by ArgoCD Image Updater
        image: nitesh287/my-image-name:{{ argocd-image-updater.argoproj.io.latest-image-tag }}