apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: prod
  annotations:
    # This is the name of the image you want to track
    argocd-image-updater.argoproj.io/image-list: nitesh287/my-image-name
    # Write-back method to update the GitHub repository
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: branch:main  # Specify the target branch to commit the changes
    # Update strategy, always use the latest tag
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        # Only the image name, ArgoCD Image Updater will dynamically update the tag
        image: nitesh287/my-image-name
