name: app deployment via Helm

on:
  push:
    branches:
      - main


jobs: 
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
    
