name: app deployment via Helm

on:
  push:
    branches:
      - main


jobs: 
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
    
      - name: Google Cloud Login
        uses: google-github-actions/auth@v2.1.0
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          token_format: access_token 

      - name: Create cluster
        run: |
          gcloud container clusters create gke-cluster --zone=us-central1-a --num-nodes=2 --disk-size=10 || echo "Cluster already exists"
          
      - name: Verify cluster is created
        run: |
          gcloud container clusters list 

      - name: Get cluster credentials 
        uses: google-github-actions/get-gke-credentials@v1 
        with:
          cluster_name: gke-cluster
          location: us-central1
          project: nitesh-gcp-444718

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          cd ./happy-helming
          helm package ./end-to-end-deployment
          ls -l
      
      - name: insall ingress controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      - name: verify installion 
        run: |
          kubectl get pods -n ingress-nginx

      - name: Installing application via helm
        run: |
          # Ensure chart is packaged and ready before installing
          helm install end-to-end-deployment ./happy-helming/end-to-end-deployment-*.tgz



        