name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'cicd-python-app/**'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
       
      - name: Extracting commit SHA 
        run: |
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "Commit SHA: ${COMMIT_SHA}"


      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: ./cicd-python-app/
          file: ./cicd-python-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-image-1:$COMMIT_SHA

  update-newtag-in-helm-chart:
      runs-on: ubuntu-latest
      
      needs: build-and-push
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "$COMMIT_SHA"/' helm-gke-deployment/simple-deployment/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "kumarmnitesh@gmail.com"
          git config --global user.name "niteshkumarm287"
          git pull
          git add helm-gke-deployment/simple-deployment/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
