name: app deployment via Helm

on:
  push:
    branches:
      - main


jobs: 
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
    
      - name: Google Cloud Login
        uses: google-github-actions/auth@v2.1.0
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          token_format: access_token 

      - name: Create cluster
        run: |
          gcloud container clusters create gke-cluster --region=us-central1 --num-nodes=2 --disk-size=10 || echo "Cluster already exists"
          
      - name: Verify cluster is created
        run: |
          gcloud container clusters list 

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          cd ./happy-helming
          helm package ./end-to-end-deployment
          ls -l