name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: ./Python_App/
          file: ./Python_App/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-image-1:${{github.run_id}}

  update-newtag-in-helm-chart:
      runs-on: ubuntu-latest
      
      needs: build-and-push
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm-gke-deployment/simple-deployment/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "kumarmnitesh@gmail.com"
          git config --global user.name "niteshkumarm287"
          git add helm-gke-deployment\simple-deployment\values.yaml
          git commit -m "Update tag in Helm chart"
          git push