name: Cluster Create Automation

on:
  push:
    branches:
      - main

jobs:
  cluster-create-automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          create_credentials_file: true 

      - name: Create cluster
        run: |
          gcloud container clusters create gke-cluster --region=us-central1 --num-nodes=2 --disk-size=10 || echo "Cluster already exists"
          
      - name: Verify cluster is created
        run: |
          gcloud container clusters list 

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install kubectl -y
          sudo apt-get upgrade kubectl -y
          kubectl version --client

      - name: Install GKE Authentication Plugin (gke-gcloud-auth-plugin)
        run: |
          # Determine system architecture (amd64 or arm64)
          ARCH=$(uname -m)
          if [ "$ARCH" == "x86_64" ]; then
            ARCH="amd64"
          elif [ "$ARCH" == "aarch64" ]; then
            ARCH="arm64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          
          # Download the correct plugin for the architecture
          curl -sSL https://github.com/GoogleCloudPlatform/k8s-container-engine-samples/releases/download/v0.0.5/gke-gcloud-auth-plugin-linux-$ARCH -o /usr/local/bin/gke-gcloud-auth-plugin
          sudo chmod +x /usr/local/bin/gke-gcloud-auth-plugin
          echo "gke-gcloud-auth-plugin installed successfully"

      - name: Connect to cluster
        run: |
          # Ensure gcloud CLI is configured and authenticate using the plugin
          gcloud container clusters get-credentials gke-cluster --region us-central1 --project nitesh-gcp-444718

      # - name: Install ArgoCD
      #   run: |
      #     kubectl create namespace argocd
      #     kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      # - name: Verify ArgoCD installation
      #   run: |
      #     kubectl get pods -n argocd

      - name: Test
        run: |
          kubectl get pods -n default
