name: Cluster Create Automation

on:
  push:
    branches:
      - main

jobs:
  cluster-create-automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          create_credentials_file: true 

      - name: Create cluster
        run: |
          gcloud container clusters create gke-cluster --region=us-central1 --num-nodes=2 --disk-size=10 || echo "Cluster already exists"
          
      - name: Verify cluster is created
        run: |
          gcloud container clusters list 

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install kubectl -y
          sudo apt-get upgrade kubectl -y
          kubectl version --client

      - name: Install GKE Authentication Plugin (gke-gcloud-auth-plugin)
        run: |
          # Update the components and attempt plugin installation
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin -q
          
      - name: Verify Plugin Installation
        run: |
          # Verify if the plugin is installed
          gcloud components list | grep gke-gcloud-auth-plugin || echo "gke-gcloud-auth-plugin not installed"
          
      - name: Connect to cluster
        run: |
          # Ensure the plugin is active and try to connect
          gcloud container clusters get-credentials gke-cluster --region us-central1 --project nitesh-gcp-444718

      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Verify ArgoCD installation
        run: |
          kubectl get pods -n argocd
