name: cluster create automation

on:
  push:
    branches:
      - main

jobs:
  cluster-create-automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          create_credentials_file: true 

      - name: create cluster
        run: |
          gcloud container clusters create gke-cluster --region=us-central1 --num-nodes=2 --disk-size=10 || echo "cluster already exists"
          

      - name: verify cluster is created
        run: |
          gcloud container clusters list 

      - name: install kubectl plugins
        run: |
          sudo apt-get install kubectl


      - name: connect  to cluster
        run: |
          gcloud container clusters get-credentials gke-cluster --region us-central1 --project nitesh-gcp-444718

      - name: Install argocd
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: verify argocd installation
        run: |
          kubectl get pods -n argocd




