name: Cluster Create Automation

on:
  push:
    branches:
      - main

jobs:
  cluster-create-automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"
          create_credentials_file: true 

      - name: Create cluster
        run: |
          gcloud container clusters create gke-cluster --region=us-central1 --num-nodes=2 --disk-size=10 || echo "Cluster already exists"
          
      - name: Verify cluster is created
        run: |
          gcloud container clusters list 

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install kubectl -y
          sudo apt-get upgrade kubectl -y
          kubectl version --client

      - name: Install GKE Authentication Plugin
        run: |
          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
          
      - name: Connect to cluster
        run: |
          # Install Google Cloud SDK
          curl -sSL https://sdk.cloud.google.com | bash
          # Restart shell to make gcloud available
          source "$HOME/google-cloud-sdk/path.bash.inc"
          # Install GKE Authentication Plugin
          gcloud components install gke-gcloud-auth-plugin -q
          
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Verify ArgoCD installation
        run: |
          kubectl get pods -n argocd
