name: Helm Package Builder and Uploader

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Google Cloud Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker

      - name: Package Helm Chart
        run: |
          cd ./helm-gke-deployment/simple-deployment
          helm package . --destination ../packages
          ls -l ../packages

      - name: Push Helm Chart to Artifact Registry
        run: |
          cd ../packages
          helm push simple-deployment-1.0.0.tgz oci://us-central1-docker.pkg.dev/nitesh-gcp-444718/simple-application
