name: helm package builder and uploader

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: google cloud login 
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"

      - name: helm setup 
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: configure helm for Artifact Registry
        run: |
          gcloud auth configure-docker
          helm repo add simple-application oci://us-central1-docker.pkg.dev/nitesh-gcp-444718/simple-application helm-gke-deployment/

      - name: helm package
        run: |
          helm ./chart-directory
          ls -l 

      - name: helm push to Artifactory
        run: |
          helm push simple-deployment-* oci://us-central1-docker.pkg.dev/nitesh-gcp-444718/simple-application helm-gke-deployment/

