name: Docker Image Smoke Test and Scanning

on:
  push:
    branches:
      - main

jobs:
  smoke-test-and-scanning:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple_python_app:v1 ./simple_python_app/ || {
            echo "Docker build failed. Exiting.";
            exit 1;
          }

      - name: Run Docker Image (Smoke Test)
        run: |
          echo "Running Docker Container..."
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/simple_python_app:v1 || {
            echo "Docker container failed to run. Exiting without pushing image.";
            exit 1;
          }
          echo "Smoke test passed successfully."

      - name: Push Docker Image
        run: |
          echo "Pushing Docker Image..."
          docker push ${{ secrets.DOCKER_USERNAME }}/simple_python_app:v1 || {
            echo "Docker push failed. Exiting.";
            exit 1;
          }
          echo "Image pushed successfully."
