name: Terraform GCP Setup

on:
  push:
    paths:
      - 'resource-creation-using-tf/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP using Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1091294306406/locations/global/workloadIdentityPools/github-gha/providers/github"
          service_account: "gha-sa@nitesh-gcp-444718.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Terraform Init 
        run: cd resource-creation-using-tf && terraform init 

      - name: Terraform Plan
        run: cd resource-creation-using-tf && terraform plan -var-file="terraform.tfvars"
